/** Whole-cell English strings that appear in tables, translated beside the chrome. */
const enKeys = [
  "admitted", "quarantine", "rejected", "pending", "confirmed", "allow", "conditional", "deny",
  "fixture", "unavailable", "not run", "pass", "fail", "high", "standard", "low", "partial",
  "unqualified", "open", "shadow", "guarded", "stopped", "present", "missing", "blocked",
  "verified", "Record", "Task", "Review", "Policy", "Train", "Validation", "Production",
  "Novelty", "Fit", "Safety", "Name", "Class", "Qualification", "Adapter", "Status",
  "Verdict", "Gate", "Subject", "Decision", "State", "Failure", "Context", "Request",
  "Count", "Deployment", "Embodiment", "Origin", "Event", "When", "Summary", "Proposed",
  "Admit", "Quarantine", "Reject", "Allow", "Conditional", "Deny", "Mark scheduled", "Dismiss",
  "Transparent container grasp", "Open medicine drawer", "Fold a cloth flat", "Pour into a cup",
  "Hand an object to a person", "Pick a mug by the handle", "Open a latched cupboard",
  "Corridor approach to a bench", "Stack two boxes", "Place a tool, person in the workspace",
  "Regrasp a transparent lid", "Draw a tray from a rack", "Premature release", "Missed lip contact",
  "capture only", "Humanoid", "Arm", "Mobile manipulator", "this session", "corpus",
] as const;

type Phrase = (typeof enKeys)[number];

function row(values: string[]): Record<Phrase, string> {
  if (values.length !== enKeys.length) throw new Error(`phrase row ${values.length} != ${enKeys.length}`);
  return Object.fromEntries(enKeys.map((key, index) => [key, values[index]])) as Record<Phrase, string>;
}

const extra: Record<string, Record<string, string>> = {
  zh: { Artifact: "制品", State: "状态", Ref: "引用", Reason: "原因", Arm: "臂", Overview: "总览" },
  es: { Artifact: "Artefacto", State: "Estado", Ref: "Ref", Reason: "Motivo", Arm: "Brazo", Overview: "Resumen" },
  fr: { Artifact: "Artefact", State: "État", Ref: "Réf", Reason: "Motif", Arm: "Bras", Overview: "Aperçu" },
  de: { Artifact: "Artefakt", State: "Zustand", Ref: "Ref", Reason: "Grund", Arm: "Arm", Overview: "Überblick" },
  ja: { Artifact: "成果物", State: "状態", Ref: "参照", Reason: "理由", Arm: "腕", Overview: "概況" },
  pt: { Artifact: "Artefacto", State: "Estado", Ref: "Ref", Reason: "Motivo", Arm: "Braço", Overview: "Síntese" },
  it: { Artifact: "Artefatto", State: "Stato", Ref: "Rif", Reason: "Motivo", Arm: "Braccio", Overview: "Quadro" },
  nl: { Artifact: "Artefact", State: "Toestand", Ref: "Ref", Reason: "Reden", Arm: "Arm", Overview: "Overzicht" },
  ru: { Artifact: "Артефакт", State: "Состояние", Ref: "Ссылка", Reason: "Причина", Arm: "Рука", Overview: "Обзор" },
  pl: { Artifact: "Artefakt", State: "Stan", Ref: "Ref", Reason: "Powód", Arm: "Ramię", Overview: "Przegląd" },
  hi: { Artifact: "कृति", State: "स्थिति", Ref: "संदर्भ", Reason: "कारण", Arm: "भुजा", Overview: "सार" },
  ar: { Artifact: "مصنوع", State: "حالة", Ref: "مرجع", Reason: "سبب", Arm: "ذراع", Overview: "نظرة" },
  ko: { Artifact: "산출물", State: "상태", Ref: "참조", Reason: "이유", Arm: "팔", Overview: "개요" },
  tr: { Artifact: "Yapıt", State: "Durum", Ref: "Ref", Reason: "Gerekçe", Arm: "Kol", Overview: "Genel bakış" },
};

export const PHRASES: Record<string, Record<string, string>> = {
  zh: row(["已准入","隔离","拒绝","待定","已确认","允许","有条件","拒绝","夹具","不可用","未运行","通过","失败","高","标准","低","部分","未鉴定","开放","影子","防护","停止","存在","缺失","受阻","已验证","记录","任务","复核","策略","训练","验证","生产","新颖","契合","安全","名称","类别","鉴定","适配器","状态","裁决","门","对象","决定","状态","失效","情境","请求","数量","部署","本体","来源","事件","时间","摘要","提议","准入","隔离","拒绝","允许","有条件","拒绝","标记已排期","驳回","透明容器抓取","打开药柜抽屉","把布折平","倒入杯中","把物体递给一个人","握住杯子把手","打开闩锁柜","沿走廊接近工作台","叠两个箱子","人在工位时放置工具","重新抓透明盖","从架上抽出托盘","过早松开","未碰到唇沿","仅采集","人形","臂","移动操作臂","本次会话","语料"]),
  es: row(["admitido","cuarentena","rechazado","pendiente","confirmado","permitir","condicional","denegar","ensayo","no disponible","sin ejecutar","pasa","falla","alta","estándar","baja","parcial","no cualificado","abierto","sombra","protegido","detenido","presente","ausente","bloqueado","verificado","Registro","Tarea","Revisión","Política","Entrenar","Validación","Producción","Novedad","Ajuste","Seguridad","Nombre","Clase","Cualificación","Adaptador","Estado","Veredicto","Puerta","Sujeto","Decisión","Estado","Fallo","Contexto","Solicitud","Cuenta","Despliegue","Cuerpo","Origen","Evento","Cuando","Resumen","Propuesto","Admitir","Cuarentena","Rechazar","Permitir","Condicional","Denegar","Marcar programado","Descartar","Agarre de recipiente transparente","Abrir cajón de medicinas","Doblar una tela","Verter en una taza","Entregar un objeto a una persona","Tomar una taza por el asa","Abrir un armario con pestillo","Acercarse por el pasillo a un banco","Apilar dos cajas","Colocar una herramienta con una persona en el puesto","Volver a agarrar una tapa transparente","Sacar una bandeja de un estante","Soltar antes de tiempo","Contacto fallido con el borde","solo captura","Humanoide","Brazo","Manipulador móvil","esta sesión","corpus"]),
  fr: row(["admis","quarantaine","rejeté","en attente","confirmé","autoriser","conditionnel","refuser","essai","indisponible","non exécuté","réussi","échec","haute","standard","basse","partiel","non qualifié","ouvert","ombre","gardé","arrêté","présent","manquant","bloqué","vérifié","Enregistrement","Tâche","Revue","Politique","Entraîner","Validation","Production","Nouveauté","Ajustement","Sûreté","Nom","Classe","Qualification","Adaptateur","État","Verdict","Porte","Sujet","Décision","État","Échec","Contexte","Demande","Compte","Déploiement","Corps","Origine","Événement","Quand","Résumé","Proposé","Admettre","Quarantaine","Rejeter","Autoriser","Conditionnel","Refuser","Marquer planifié","Écarter","Saisie d’un récipient transparent","Ouvrir un tiroir à médicaments","Plier un tissu à plat","Verser dans une tasse","Donner un objet à une personne","Prendre une tasse par l’anse","Ouvrir un placard à loquet","Approche de couloir vers un établi","Empiler deux boîtes","Poser un outil avec une personne au poste","Resaisir un couvercle transparent","Tirer un plateau d’une étagère","Lâcher trop tôt","Contact manqué sur le bord","capture seule","Humanoïde","Bras","Manipulateur mobile","cette session","corpus"]),
  de: row(["zugelassen","Quarantäne","abgelehnt","offen","bestätigt","erlauben","bedingt","ablehnen","Prüfung","nicht verfügbar","nicht gelaufen","bestanden","fehlgeschlagen","hoch","standard","niedrig","teilweise","unqualifiziert","offen","Schatten","bewacht","gestoppt","vorhanden","fehlend","blockiert","verifiziert","Eintrag","Aufgabe","Prüfung","Richtlinie","Trainieren","Validierung","Produktion","Neuheit","Passung","Sicherheit","Name","Klasse","Qualifikation","Adapter","Status","Urteil","Tor","Subjekt","Entscheidung","Zustand","Fehler","Kontext","Anfrage","Anzahl","Einsatz","Verkörperung","Herkunft","Ereignis","Wann","Zusammenfassung","Vorgeschlagen","Zulassen","Quarantäne","Ablehnen","Erlauben","Bedingt","Ablehnen","Als geplant markieren","Verwerfen","Griff an transparentem Behälter","Medizinschublade öffnen","Tuch flach falten","In eine Tasse gießen","Einen Gegenstand einer Person reichen","Tasse am Henkel greifen","Schrank mit Riegel öffnen","Flurannäherung an eine Bank","Zwei Kisten stapeln","Werkzeug ablegen, Person am Platz","Transparenten Deckel neu greifen","Tablett aus einem Regal ziehen","Zu frühes Loslassen","Randkontakt verfehlt","nur Aufnahme","Humanoid","Arm","Mobiler Manipulator","diese Sitzung","Korpus"]),
  ja: row(["受理","隔離","拒否","保留","確認済み","許可","条件付き","拒否","治具","使用不可","未実行","合格","失敗","高","標準","低","部分","未認定","開","影","防護","停止","存在","欠落","阻止","検証済み","記録","課題","再確認","方針","学習","検証","本番","新規性","適合","安全","名前","類","認定","接続口","状態","判定","門","対象","決定","状態","失敗","状況","要求","件数","配備","身体","由来","事象","時刻","要約","提案","受理する","隔離する","拒否する","許可する","条件付き","拒否する","予定済みにする","棄却","透明容器の把持","薬引き出しを開ける","布を平らに畳む","杯に注ぐ","人に物を渡す","取っ手で杯を持つ","掛け金の戸棚を開ける","廊下から作業台へ近づく","箱を二つ積む","人がいる作業台に工具を置く","透明な蓋を掴み直す","棚から盆を引く","早すぎる解放","縁に触れ損ねる","収集のみ","人型","腕","移動マニピュレータ","このセッション","コーパス"]),
  pt: row(["admitido","quarentena","rejeitado","pendente","confirmado","permitir","condicional","recusar","ensaio","indisponível","não executado","passa","falha","alta","padrão","baixa","parcial","não qualificado","aberto","sombra","guardado","parado","presente","em falta","bloqueado","verificado","Registo","Tarefa","Revisão","Política","Treinar","Validação","Produção","Novidade","Ajuste","Segurança","Nome","Classe","Qualificação","Adaptador","Estado","Veredicto","Porta","Sujeito","Decisão","Estado","Falha","Contexto","Pedido","Conta","Implantação","Corpo","Origem","Evento","Quando","Resumo","Proposto","Admitir","Quarentena","Rejeitar","Permitir","Condicional","Recusar","Marcar agendado","Dispensar","Agarre de recipiente transparente","Abrir gaveta de medicamentos","Dobrar um pano","Verter numa chávena","Entregar um objeto a uma pessoa","Pegar uma chávena pela asa","Abrir um armário com trinco","Aproximação de corredor a uma banca","Empilhar duas caixas","Colocar uma ferramenta com uma pessoa no posto","Voltar a agarrar uma tampa transparente","Puxar um tabuleiro de uma estante","Largar cedo demais","Contacto falhado no bordo","só captura","Humanoide","Braço","Manipulador móvel","esta sessão","corpus"]),
  it: row(["ammesso","quarantena","rifiutato","in attesa","confermato","consenti","condizionale","nega","prova","non disponibile","non eseguito","passa","fallisce","alta","standard","bassa","parziale","non qualificato","aperto","ombra","protetto","fermo","presente","mancante","bloccato","verificato","Record","Compito","Revisione","Policy","Addestrare","Validazione","Produzione","Novità","Adattamento","Sicurezza","Nome","Classe","Qualificazione","Adattatore","Stato","Verdetto","Cancello","Soggetto","Decisione","Stato","Guasto","Contesto","Richiesta","Conto","Dispiegamento","Corpo","Origine","Evento","Quando","Sintesi","Proposto","Ammetti","Quarantena","Rifiuta","Consenti","Condizionale","Nega","Segna pianificato","Scarta","Presa di un contenitore trasparente","Aprire un cassetto di medicinali","Piegare un panno","Versare in una tazza","Dare un oggetto a una persona","Prendere una tazza per il manico","Aprire un armadio con chiavistello","Avvicinarsi dal corridoio a un banco","Impilare due scatole","Posare un utensile con una persona al banco","Riafferrare un coperchio trasparente","Estrarre un vassoio da uno scaffale","Rilascio prematuro","Contatto mancato sul bordo","solo cattura","Umanoide","Braccio","Manipolatore mobile","questa sessione","corpus"]),
  nl: row(["toegelaten","quarantaine","afgewezen","open","bevestigd","toestaan","voorwaardelijk","weigeren","proef","niet beschikbaar","niet uitgevoerd","geslaagd","mislukt","hoog","standaard","laag","gedeeltelijk","ongekwalificeerd","open","schaduw","bewaakt","gestopt","aanwezig","ontbrekend","geblokkeerd","geverifieerd","Record","Taak","Beoordeling","Beleid","Trainen","Validatie","Productie","Nieuwheid","Passing","Veiligheid","Naam","Klasse","Kwalificatie","Adapter","Status","Uitspraak","Poort","Onderwerp","Besluit","Toestand","Fout","Context","Verzoek","Aantal","Inzet","Lichaam","Herkomst","Gebeurtenis","Wanneer","Samenvatting","Voorgesteld","Toelaten","Quarantaine","Afwijzen","Toestaan","Voorwaardelijk","Weigeren","Als gepland markeren","Verwerpen","Greep op doorzichtige houder","Medicijnlade openen","Doek vlak vouwen","In een kop gieten","Een voorwerp aan een persoon geven","Kop aan het oor pakken","Kast met grendel openen","Gangnadering naar een bank","Twee dozen stapelen","Gereedschap plaatsen, persoon op de plek","Doorzichtig deksel opnieuw grijpen","Blad uit een rek trekken","Te vroeg loslaten","Randcontact gemist","alleen opname","Humanoïde","Arm","Mobiele manipulator","deze sessie","corpus"]),
  ru: row(["допущен","карантин","отклонён","ожидает","подтверждён","разрешить","условно","отказать","испытание","недоступно","не выполнен","пройден","сбой","высокая","стандарт","низкая","частично","не аттестован","открыт","тень","под защитой","остановлен","есть","нет","заблокирован","проверен","Запись","Задача","Проверка","Политика","Обучение","Проверка","Прод","Новизна","Совместимость","Безопасность","Имя","Класс","Квалификация","Адаптер","Статус","Вердикт","Ворота","Субъект","Решение","Состояние","Отказ","Контекст","Запрос","Число","Развёртывание","Тело","Источник","Событие","Когда","Сводка","Предложено","Допустить","Карантин","Отклонить","Разрешить","Условно","Отказать","Отметить запланированным","Отклонить запрос","Захват прозрачного сосуда","Открыть ящик с лекарствами","Сложить ткань","Налить в чашку","Передать предмет человеку","Взять чашку за ручку","Открыть шкаф с задвижкой","Подход по коридору к столу","Сложить две коробки","Положить инструмент, человек у места","Снова схватить прозрачную крышку","Вытянуть лоток с полки","Преждевременное отпускание","Промах по кромке","только съём","Гуманоид","Рука","Мобильный манипулятор","этот сеанс","корпус"]),
  pl: row(["dopuszczony","kwarantanna","odrzucony","oczekuje","potwierdzony","zezwól","warunkowo","odmów","próba","niedostępny","nie wykonano","zaliczony","błąd","wysoka","standard","niska","częściowa","niekwalifikowany","otwarty","cień","chroniony","zatrzymany","obecny","brak","zablokowany","zweryfikowany","Rekord","Zadanie","Przegląd","Polityka","Trening","Walidacja","Produkcja","Nowość","Dopasowanie","Bezpieczeństwo","Nazwa","Klasa","Kwalifikacja","Adapter","Stan","Werdykt","Brama","Podmiot","Decyzja","Stan","Awaria","Kontekst","Prośba","Liczba","Wdrożenie","Ciało","Pochodzenie","Zdarzenie","Kiedy","Streszczenie","Proponowane","Dopuść","Kwarantanna","Odrzuć","Zezwól","Warunkowo","Odmów","Oznacz jako zaplanowane","Odrzuć prośbę","Chwyt przezroczystego naczynia","Otwórz szufladę z lekami","Złóż tkaninę na płasko","Nalej do kubka","Podaj przedmiot osobie","Chwyć kubek za ucho","Otwórz szafkę z zasuwką","Podejście korytarzem do stołu","Ułóż dwa pudła","Odłóż narzędzie, osoba przy stanowisku","Ponownie chwyć przezroczystą pokrywkę","Wysuń tacę z półki","Zbyt wczesne puszczenie","Chybiony kontakt z krawędzią","tylko nagranie","Humanoid","Ramię","Manipulator mobilny","ta sesja","korpus"]),
  hi: row(["स्वीकृत","संगरोध","अस्वीकृत","लंबित","पुष्ट","अनुमति","सशर्त","अस्वीकार","परीक्षण","अनुपलब्ध","नहीं चला","उत्तीर्ण","असफल","उच्च","मानक","निम्न","आंशिक","अयोग्य","खुला","छाया","रक्षित","रुका","उपस्थित","अनुपस्थित","अवरुद्ध","सत्यापित","अभिलेख","कार्य","समीक्षा","नीति","प्रशिक्षण","सत्यापन","उत्पादन","नवीनता","फिट","सुरक्षा","नाम","वर्ग","योग्यता","अनुकूलक","स्थिति","निर्णय","द्वार","विषय","निर्णय","स्थिति","विफलता","संदर्भ","अनुरोध","संख्या","परिनियोजन","शरीर","मूल","घटना","कब","सार","प्रस्तावित","स्वीकारें","संगरोध","अस्वीकारें","अनुमति","सशर्त","अस्वीकार","निर्धारित चिह्नित करें","खारिज","पारदर्शी पात्र पकड़","दवा दराज खोलें","कपड़ा समतल मोड़ें","कप में डालें","वस्तु व्यक्ति को दें","हत्थे से मग पकड़ें","कुंडी अलमारी खोलें","गलियारे से बेंच तक","दो डिब्बे रखें","व्यक्ति के साथ उपकरण रखें","पारदर्शी ढक्कन पुनः पकड़ें","रैक से ट्रे निकालें","समय से पहले छोड़ना","किनारे का संपर्क चूका","केवल संग्रह","मानवाकार","भुजा","चल प्रचालक","यह सत्र","संग्रह"]),
  ar: row(["مقبول","حجر","مرفوض","معلّق","مؤكَّد","اسمح","مشروط","ارفض","اختبار","غير متاح","لم يُشغَّل","نجاح","فشل","عالٍ","قياسي","منخفض","جزئي","غير مؤهَّل","مفتوح","ظل","محروس","متوقف","موجود","مفقود","محجوب","متحقق","سجل","مهمة","مراجعة","سياسة","تدريب","تحقق","إنتاج","جدة","ملاءمة","سلامة","اسم","فئة","تأهيل","مهايئ","حالة","حكم","بوابة","موضوع","قرار","حالة","إخفاق","سياق","طلب","عدد","نشر","جسم","أصل","حدث","متى","ملخص","مقترح","اقبل","حجر","ارفض","اسمح","مشروط","ارفض","علّم مجدولًا","اصرف","إمساك وعاء شفاف","فتح درج دواء","طي قماش","صب في فنجان","مناولة شيء لشخص","إمساك كوب من المقبض","فتح خزانة بمزلاج","اقتراب الممر من طاولة","رص صندوقين","وضع أداة وشخص في المكان","إعادة إمساك غطاء شفاف","سحب صينية من رف","إفلات مبكر","إخفاق لمس الحافة","التقاط فقط","بشري الشكل","ذراع","مناور متحرّك","هذه الجلسة","متن"]),
  ko: row(["입학","격리","거부","대기","확인","허용","조건부","거부","시험","사용 불가","미실행","통과","실패","높음","표준","낮음","부분","미인증","열림","그림자","보호","정지","있음","없음","막힘","검증됨","기록","과제","재검토","정책","학습","검증","생산","참신","적합","안전","이름","종류","인증","어댑터","상태","판정","문","대상","결정","상태","실패","맥락","요청","수","배치","몸체","출처","사건","때","요약","제안","받아들이다","격리","거부","허용","조건부","거부","일정 표시","기각","투명 용기 파지","약 서랍 열기","천을 평평히 접기","잔에 따르기","사람에게 물건 건네기","손잡이로 잔 잡기","걸쇠 찬장 열기","복도에서 작업대로","상자 두 개 쌓기","사람이 있는 곳에 도구 놓기","투명 뚜껑 다시 잡기","선반에서 쟁반 빼기","너무 이른 놓음","가장자리 접촉 실패","수집만","인간형","팔","이동 매니퓰레이터","이 세션","말뭉치"]),
  tr: row(["kabul","karantina","red","bekliyor","onaylı","izin","koşullu","ret","deneme","yok","çalışmadı","geçer","olmaz","yüksek","standart","düşük","kısmi","nitelenmemiş","açık","gölge","korumalı","durdu","var","eksik","engelli","doğrulandı","Kayıt","Görev","İnceleme","İlke","Eğitim","Doğrulama","Üretim","Yenilik","Uyum","Güvenlik","Ad","Sınıf","Nitelik","Bağdaştırıcı","Durum","Hüküm","Kapı","Özne","Karar","Durum","Arıza","Bağlam","İstek","Sayı","Konuşlandırma","Gövde","Köken","Olay","Ne zaman","Özet","Önerilen","Kabul et","Karantina","Reddet","İzin ver","Koşullu","Reddet","Planlandı işaretle","Düşür","Saydam kap tutuşu","İlaç çekmecesini aç","Bezi düz katla","Fincana dök","Bir nesneyi kişiye ver","Kulptan fincan tut","Mandalı dolabı aç","Koridordan tezgâha yaklaş","İki kutu istif","Kişi varken alet koy","Saydam kapağı yeniden tut","Raftan tepsi çek","Erken bırakma","Kenar teması kaçtı","yalnız çekim","İnsansı","Kol","Gezgin manipülatör","bu oturum","bütünce"]),
};

for (const [id, map] of Object.entries(extra)) {
  PHRASES[id] = { ...(PHRASES[id] ?? {}), ...map };
}
